Add blog and article settings editor
Voog/design-rotterdam pull request #113
Opened 2021-06-07 10:42 UTC by pxska

Closes #112

2021-06-07 13:39 UTC, siimha requested changes
Kuna ma ei leia hetkel muid probleeme ja ei taha kohe ka approve panna, siis võiksid main.js-ist tuua ka teised muutmise vaate scriptid editmode.js-i.

2021-06-08 14:03 UTC, tanelj requested changes
Kas oskad öelda, miks "images" kasuta pildid suuremaks läksid? Nt:

images/front-page-header-bg.jpg 170K -> 174K
images/search.png   288B -> 1.2K

2021-06-08 14:03 UTC, tanelj commented on sources/stylesheets/_variables.scss
> +$primary-font: $avenir;
`$primary-font` muutuja nimena tundub veidi kahtlane - võiks viidata nagu oleks tegu malli peamise fontiga, tegelikult vaid pm ühe seadete nupuga seotud.

2021-06-09 06:18 UTC, pxska commented
Pildid läksid suuremaks, sest mul olid Grunti jooksutades piltide minifierid puudu – need on nüüd tagasi ja peaks olema korras.

2021-06-09 08:10 UTC, siimha commented
Artikli vaates renderdatakse seadete nupp alguses õhku ja lennutatakse siis renderdusel õigesse kohta:
https://user-images.githubusercontent.com/35253483/121317675-34a93c80-c913-11eb-8026-b225761f0758.mov

2021-06-09 13:14 UTC, tanelj approved these changes

2021-06-09 13:46 UTC, siimha approved these changes

2021-06-09 13:48 UTC, merged